on:
  push:
    branch:
      - '*'
  pull_request:
    branches:
      - '*'

name: 'Trigger: Push action'

jobs:
  shellcheck:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
